In [12]:
import numpy as np
np.random.seed(0)
marks=np.random.randint(35,100,size=(100,5))
print("Dataset:\n",marks)


Dataset:
 [[79 82 99 44 56]
 [71 47 93 74 81]
 [72 60 44 55 82]
 [99 84 64 54 54]
 [49 74 67 44 92]
 [67 66 58 70 90]
 [63 69 35 35 71]
 [88 40 73 52 39]
 [77 93 66 36 76]
 [92 70 46 81 35]
 [49 88 47 77 41]
 [82 38 87 50 55]
 [93 58 48 83 84]
 [76 70 99 35 85]
 [71 69 83 38 77]
 [56 35 45 78 93]
 [58 94 37 97 70]
 [81 55 85 62 49]
 [76 93 71 45 78]
 [46 37 86 67 89]
 [35 73 54 81 77]
 [91 95 65 59 37]
 [38 48 75 54 61]
 [87 96 49 39 46]
 [91 51 59 64 56]
 [60 95 96 68 67]
 [66 48 91 59 76]
 [53 75 89 46 73]
 [36 79 59 38 70]
 [96 78 67 46 45]
 [89 72 63 37 62]
 [58 88 86 81 55]
 [88 64 70 74 44]
 [76 58 38 81 85]
 [38 66 44 45 62]
 [80 74 96 79 69]
 [69 68 40 71 35]
 [69 88 97 43 96]
 [36 70 75 71 83]
 [60 70 65 64 68]
 [53 52 37 47 79]
 [74 74 57 65 52]
 [53 78 84 76 81]
 [56 63 93 35 98]
 [51 71 59 98 86]
 [43 91 67 54 48]
 [93 90 99 71 60]
 [67 77 49 63 55]
 [57 42 96 48 40]
 [35 43 88 46 39]
 [74 80 61 87 84]
 [86 53 69 86 65]
 [88 93 78 90 53]
 [80 88 83 94 61]
 [70 93 84 79 48]


In [14]:
print("\nShape:",marks.shape)
print("Dimensions:",marks.ndim)
print("Total Elements:",marks.size)


Shape: (100, 5)
Dimensions: 2
Total Elements: 500


In [17]:
print("\nFirst Student:",marks[0,:])
print("Math Column:",marks[:,0])
print("First 5 Students:\n",marks[0:5:,1])
print("physics & Chemistry:\n",marks[:,1:3])
print("Specific students:\n",marks[:,1:3])
print("Specific Students:\n",marks[[0,10,25],:])
print("Marks>90:",marks[marks>90])


First Student: [79 82 99 44 56]
Math Column: [79 71 72 99 49 67 63 88 77 92 49 82 93 76 71 56 58 81 76 46 35 91 38 87
 91 60 66 53 36 96 89 58 88 76 38 80 69 69 36 60 53 74 53 56 51 43 93 67
 57 35 74 86 88 80 70 73 57 91 65 58 86 71 71 66 53 36 71 68 68 65 81 67
 80 55 39 57 82 80 88 85 62 95 63 70 51 47 82 38 59 84 42 47 81 42 86 55
 83 72 85 59]
First 5 Students:
 [82 47 60 84 74]
physics & Chemistry:
 [[82 99]
 [47 93]
 [60 44]
 [84 64]
 [74 67]
 [66 58]
 [69 35]
 [40 73]
 [93 66]
 [70 46]
 [88 47]
 [38 87]
 [58 48]
 [70 99]
 [69 83]
 [35 45]
 [94 37]
 [55 85]
 [93 71]
 [37 86]
 [73 54]
 [95 65]
 [48 75]
 [96 49]
 [51 59]
 [95 96]
 [48 91]
 [75 89]
 [79 59]
 [78 67]
 [72 63]
 [88 86]
 [64 70]
 [58 38]
 [66 44]
 [74 96]
 [68 40]
 [88 97]
 [70 75]
 [70 65]
 [52 37]
 [74 57]
 [78 84]
 [63 93]
 [71 59]
 [91 67]
 [90 99]
 [77 49]
 [42 96]
 [43 88]
 [80 61]
 [53 69]
 [93 78]
 [88 83]
 [93 84]
 [74 43]
 [43 41]
 [58 59]
 [89 60]
 [62 64]
 [42 44]
 [55 38]
 [82 45]
 [55 44]
 [78 38]
 [35 

In [20]:
print("\nAdd Grace(+5:\n)",marks+5)
print("Increase Math by 10:\n",marks[:,0]+10)
print("Squared Marks:\n",marks**2)
math_marks=marks[:,0]
normalized=(math_marks-np.mean(math_marks))/np.std(math_marks)
print("Normalized Math Marks:\n",normalized)



Add Grace(+5:
) [[ 84  87 104  49  61]
 [ 76  52  98  79  86]
 [ 77  65  49  60  87]
 [104  89  69  59  59]
 [ 54  79  72  49  97]
 [ 72  71  63  75  95]
 [ 68  74  40  40  76]
 [ 93  45  78  57  44]
 [ 82  98  71  41  81]
 [ 97  75  51  86  40]
 [ 54  93  52  82  46]
 [ 87  43  92  55  60]
 [ 98  63  53  88  89]
 [ 81  75 104  40  90]
 [ 76  74  88  43  82]
 [ 61  40  50  83  98]
 [ 63  99  42 102  75]
 [ 86  60  90  67  54]
 [ 81  98  76  50  83]
 [ 51  42  91  72  94]
 [ 40  78  59  86  82]
 [ 96 100  70  64  42]
 [ 43  53  80  59  66]
 [ 92 101  54  44  51]
 [ 96  56  64  69  61]
 [ 65 100 101  73  72]
 [ 71  53  96  64  81]
 [ 58  80  94  51  78]
 [ 41  84  64  43  75]
 [101  83  72  51  50]
 [ 94  77  68  42  67]
 [ 63  93  91  86  60]
 [ 93  69  75  79  49]
 [ 81  63  43  86  90]
 [ 43  71  49  50  67]
 [ 85  79 101  84  74]
 [ 74  73  45  76  40]
 [ 74  93 102  48 101]
 [ 41  75  80  76  88]
 [ 65  75  70  69  73]
 [ 58  57  42  52  84]
 [ 79  79  62  70  57]
 [ 58  83  89  81

In [22]:
weights=np.array([1.0,0.9,0.8,0.7,1.2])
weighted_marks = marks*weights
print("\nWeighted Mraks:\n",weighted_marks)
total=np.sum(marks,axis=1)
print("Total per Student:\n",total)
avg_subject=np.mean(marks,axis=0)
print("Average per student:\n",avg_subject)



Weighted Mraks:
 [[ 79.   73.8  79.2  30.8  67.2]
 [ 71.   42.3  74.4  51.8  97.2]
 [ 72.   54.   35.2  38.5  98.4]
 [ 99.   75.6  51.2  37.8  64.8]
 [ 49.   66.6  53.6  30.8 110.4]
 [ 67.   59.4  46.4  49.  108. ]
 [ 63.   62.1  28.   24.5  85.2]
 [ 88.   36.   58.4  36.4  46.8]
 [ 77.   83.7  52.8  25.2  91.2]
 [ 92.   63.   36.8  56.7  42. ]
 [ 49.   79.2  37.6  53.9  49.2]
 [ 82.   34.2  69.6  35.   66. ]
 [ 93.   52.2  38.4  58.1 100.8]
 [ 76.   63.   79.2  24.5 102. ]
 [ 71.   62.1  66.4  26.6  92.4]
 [ 56.   31.5  36.   54.6 111.6]
 [ 58.   84.6  29.6  67.9  84. ]
 [ 81.   49.5  68.   43.4  58.8]
 [ 76.   83.7  56.8  31.5  93.6]
 [ 46.   33.3  68.8  46.9 106.8]
 [ 35.   65.7  43.2  56.7  92.4]
 [ 91.   85.5  52.   41.3  44.4]
 [ 38.   43.2  60.   37.8  73.2]
 [ 87.   86.4  39.2  27.3  55.2]
 [ 91.   45.9  47.2  44.8  67.2]
 [ 60.   85.5  76.8  47.6  80.4]
 [ 66.   43.2  72.8  41.3  91.2]
 [ 53.   67.5  71.2  32.2  87.6]
 [ 36.   71.1  47.2  26.6  84. ]
 [ 96.   70.2  53.6  32.2

In [26]:
topper_index=np.argmax(total)
print("\nTopper Index:",topper_index)
subject_toppers=np.argmax(marks,axis=0)
print("Topper in Each Subject:",subject_toppers)
print("Failures(<40):",marks[marks<40])
avg_student=np.mean(marks,axis=1)
high_performers=marks[avg_student>75]
print("High Performers:\n",high_performers)


Topper Index: 71
Topper in Each Subject: [ 3 23  0 44 43]
Failures(<40): [35 35 39 36 35 38 35 38 35 37 37 35 37 38 39 36 38 37 38 38 35 36 37 35
 35 39 39 35 38 38 36 35 38 35 35 39 39 35 38 36 38 39 38 39 38 38 37]
High Performers:
 [[60 95 96 68 67]
 [80 74 96 79 69]
 [69 88 97 43 96]
 [93 90 99 71 60]
 [74 80 61 87 84]
 [88 93 78 90 53]
 [80 88 83 94 61]
 [67 79 94 92 85]
 [55 80 92 71 97]
 [57 86 81 96 95]
 [82 94 77 45 92]]


In [30]:
import numpy as np

data = np.random.randint(10, 50, size=(24, 24))  

print(data)



[[19 18 35 43 27 26 17 40 26 32 47 19 22 34 32 24 43 14 15 22 22 10 15 32]
 [43 11 20 16 26 17 37 48 30 28 16 48 44 20 49 37 40 46 44 35 37 41 13 10]
 [47 49 22 30 21 22 37 31 22 27 49 41 39 11 47 10 33 23 18 30 28 26 23 18]
 [16 37 47 45 36 40 22 26 33 18 26 28 20 25 48 34 46 10 13 36 30 43 34 28]
 [19 18 17 38 29 32 13 24 12 33 34 30 45 42 44 38 47 46 28 45 49 45 11 39]
 [30 47 45 44 37 24 40 37 14 14 16 13 49 46 37 23 10 20 39 24 10 10 42 21]
 [39 15 15 40 28 26 27 21 19 19 36 22 10 49 38 23 33 37 35 30 22 34 15 44]
 [22 25 31 46 22 44 15 30 41 44 33 29 31 16 14 19 34 42 20 36 37 26 44 32]
 [38 38 24 47 35 15 12 45 21 23 45 41 40 15 39 37 11 36 38 49 49 43 42 14]
 [10 21 45 14 36 25 38 26 16 41 12 27 11 42 43 48 14 40 14 25 31 48 20 26]
 [12 42 49 33 11 46 35 18 37 10 45 36 32 41 11 39 13 13 44 46 30 15 34 29]
 [47 13 29 33 40 40 35 17 22 14 37 22 20 20 16 17 10 44 42 33 10 17 40 28]
 [42 12 48 22 10 18 13 23 36 13 48 16 16 30 12 31 28 26 43 15 39 25 35 34]
 [46 10 23 22 16 13 42 45

In [31]:
data_3d = data.reshape(3, 8, 24)

threshold = 40

print(data)

[[19 18 35 43 27 26 17 40 26 32 47 19 22 34 32 24 43 14 15 22 22 10 15 32]
 [43 11 20 16 26 17 37 48 30 28 16 48 44 20 49 37 40 46 44 35 37 41 13 10]
 [47 49 22 30 21 22 37 31 22 27 49 41 39 11 47 10 33 23 18 30 28 26 23 18]
 [16 37 47 45 36 40 22 26 33 18 26 28 20 25 48 34 46 10 13 36 30 43 34 28]
 [19 18 17 38 29 32 13 24 12 33 34 30 45 42 44 38 47 46 28 45 49 45 11 39]
 [30 47 45 44 37 24 40 37 14 14 16 13 49 46 37 23 10 20 39 24 10 10 42 21]
 [39 15 15 40 28 26 27 21 19 19 36 22 10 49 38 23 33 37 35 30 22 34 15 44]
 [22 25 31 46 22 44 15 30 41 44 33 29 31 16 14 19 34 42 20 36 37 26 44 32]
 [38 38 24 47 35 15 12 45 21 23 45 41 40 15 39 37 11 36 38 49 49 43 42 14]
 [10 21 45 14 36 25 38 26 16 41 12 27 11 42 43 48 14 40 14 25 31 48 20 26]
 [12 42 49 33 11 46 35 18 37 10 45 36 32 41 11 39 13 13 44 46 30 15 34 29]
 [47 13 29 33 40 40 35 17 22 14 37 22 20 20 16 17 10 44 42 33 10 17 40 28]
 [42 12 48 22 10 18 13 23 36 13 48 16 16 30 12 31 28 26 43 15 39 25 35 34]
 [46 10 23 22 16 13 42 45

In [32]:
mask = data_3d > threshold
print(data)

[[19 18 35 43 27 26 17 40 26 32 47 19 22 34 32 24 43 14 15 22 22 10 15 32]
 [43 11 20 16 26 17 37 48 30 28 16 48 44 20 49 37 40 46 44 35 37 41 13 10]
 [47 49 22 30 21 22 37 31 22 27 49 41 39 11 47 10 33 23 18 30 28 26 23 18]
 [16 37 47 45 36 40 22 26 33 18 26 28 20 25 48 34 46 10 13 36 30 43 34 28]
 [19 18 17 38 29 32 13 24 12 33 34 30 45 42 44 38 47 46 28 45 49 45 11 39]
 [30 47 45 44 37 24 40 37 14 14 16 13 49 46 37 23 10 20 39 24 10 10 42 21]
 [39 15 15 40 28 26 27 21 19 19 36 22 10 49 38 23 33 37 35 30 22 34 15 44]
 [22 25 31 46 22 44 15 30 41 44 33 29 31 16 14 19 34 42 20 36 37 26 44 32]
 [38 38 24 47 35 15 12 45 21 23 45 41 40 15 39 37 11 36 38 49 49 43 42 14]
 [10 21 45 14 36 25 38 26 16 41 12 27 11 42 43 48 14 40 14 25 31 48 20 26]
 [12 42 49 33 11 46 35 18 37 10 45 36 32 41 11 39 13 13 44 46 30 15 34 29]
 [47 13 29 33 40 40 35 17 22 14 37 22 20 20 16 17 10 44 42 33 10 17 40 28]
 [42 12 48 22 10 18 13 23 36 13 48 16 16 30 12 31 28 26 43 15 39 25 35 34]
 [46 10 23 22 16 13 42 45

In [33]:
avg_temp = data_3d.mean()

data_3d[mask] = avg_temp
print(data)

[[19 18 35 28 27 26 17 40 26 32 28 19 22 34 32 24 28 14 15 22 22 10 15 32]
 [28 11 20 16 26 17 37 28 30 28 16 28 28 20 28 37 40 28 28 35 37 28 13 10]
 [28 28 22 30 21 22 37 31 22 27 28 28 39 11 28 10 33 23 18 30 28 26 23 18]
 [16 37 28 28 36 40 22 26 33 18 26 28 20 25 28 34 28 10 13 36 30 28 34 28]
 [19 18 17 38 29 32 13 24 12 33 34 30 28 28 28 38 28 28 28 28 28 28 11 39]
 [30 28 28 28 37 24 40 37 14 14 16 13 28 28 37 23 10 20 39 24 10 10 28 21]
 [39 15 15 40 28 26 27 21 19 19 36 22 10 28 38 23 33 37 35 30 22 34 15 28]
 [22 25 31 28 22 28 15 30 28 28 33 29 31 16 14 19 34 28 20 36 37 26 28 32]
 [38 38 24 28 35 15 12 28 21 23 28 28 40 15 39 37 11 36 38 28 28 28 28 14]
 [10 21 28 14 36 25 38 26 16 28 12 27 11 28 28 28 14 40 14 25 31 28 20 26]
 [12 28 28 33 11 28 35 18 37 10 28 36 32 28 11 39 13 13 28 28 30 15 34 29]
 [28 13 29 33 40 40 35 17 22 14 37 22 20 20 16 17 10 28 28 33 10 17 40 28]
 [28 12 28 22 10 18 13 23 36 13 28 16 16 30 12 31 28 26 28 15 39 25 35 34]
 [28 10 23 22 16 13 28 28

In [34]:
print("Reshaped 3D Data:\n", data_3d)
print("\nAverage Temperature:", avg_temp)

Reshaped 3D Data:
 [[[19 18 35 28 27 26 17 40 26 32 28 19 22 34 32 24 28 14 15 22 22 10 15
   32]
  [28 11 20 16 26 17 37 28 30 28 16 28 28 20 28 37 40 28 28 35 37 28 13
   10]
  [28 28 22 30 21 22 37 31 22 27 28 28 39 11 28 10 33 23 18 30 28 26 23
   18]
  [16 37 28 28 36 40 22 26 33 18 26 28 20 25 28 34 28 10 13 36 30 28 34
   28]
  [19 18 17 38 29 32 13 24 12 33 34 30 28 28 28 38 28 28 28 28 28 28 11
   39]
  [30 28 28 28 37 24 40 37 14 14 16 13 28 28 37 23 10 20 39 24 10 10 28
   21]
  [39 15 15 40 28 26 27 21 19 19 36 22 10 28 38 23 33 37 35 30 22 34 15
   28]
  [22 25 31 28 22 28 15 30 28 28 33 29 31 16 14 19 34 28 20 36 37 26 28
   32]]

 [[38 38 24 28 35 15 12 28 21 23 28 28 40 15 39 37 11 36 38 28 28 28 28
   14]
  [10 21 28 14 36 25 38 26 16 28 12 27 11 28 28 28 14 40 14 25 31 28 20
   26]
  [12 28 28 33 11 28 35 18 37 10 28 36 32 28 11 39 13 13 28 28 30 15 34
   29]
  [28 13 29 33 40 40 35 17 22 14 37 22 20 20 16 17 10 28 28 33 10 17 40
   28]
  [28 12 28 22 10 18 13 23 36 1